name: auth_repository
description: Authentication Repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0

dependencies:
  dartz: ^0.10.1
  firebase_auth: ^4.7.2
  rxdart: ^0.27.7
