name: scratch_one
description: Scratch One Music project
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  auth_repository:
    path: packages/auth_repository
  bloc: ^8.1.2
  cupertino_icons: ^1.0.5
  dropdown_button2: ^2.3.7
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  intl: ^0.18.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2

flutter:
  uses-material-design: true
