// https://flagpedia.net/emoji

const kCountryFlags = {
  'Afghanistan': {
    'description': '\u{1F1E6}\u{1F1EB} Afghanistan (+93)',
    'flag': '\u{1F1E6}\u{1F1EB}',
    'phone': '+93',
  },
  'Albania': {
    'description': '\u{1F1E6}\u{1F1F1} Albania (+355)',
    'flag': '\u{1F1E6}\u{1F1F1}',
    'phone': '+355',
  },
  'Algeria': {
    'description': '_______',
    'flag': '\u{1F1E9}\u{1F1FF}',
    'phone': '+213',
  },
  'American Samoa': {
    'description': '_______',
    'flag': '\u{1F1E6}\u{1F1F8}',
    'phone': '+1',
  },
  'Andorra': {
    'description': '_______',
    'flag': '\u{1F1E6}\u{1F1E9}',
    'phone': '+376',
  },
  'Angola': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Anguilla': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Antigua & Barbuda': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Argentina': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Aruba': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Ascension Island': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Australia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Austria': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Azerbaijan': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Åland Islands': {
    'description': '_______',
    'flag': '______',
    'phone': '+358',
  },
  'Bahamas': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Bahrain': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Bangladesh': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Barbados': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Belarus': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Belgium': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Belize': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Benin': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Bermuda': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Bhutan': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Bolivia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Bosnia & Herzegovina': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Botswana': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Brazil': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'British Virgin Islands': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Brunei': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Burkina Faso': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Burundi': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Cambodia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Cameroon': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Canada': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Cape Verde': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Caribbean Netherlands': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Cayman Islands': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Central African Republic': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Chad': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Chagos Archipelago': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Chile': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'China mainland': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Christmas Island': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Cocos (Keeling) Islands': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Columbia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Comoros': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Congo - Brazzaville': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Congo - Kinshasa': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Cook Islands': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Costa Rica': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Côte d\'lvoire': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Croatia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Cuba': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Curaçao': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Cyprus': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Czechia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Denmark': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Djibouti': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Dominica': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Dominican Republic': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Ecuador': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Egypt': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'El Salvador': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Equatorial Guinea': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Eritrea': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Estonia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Eswatini': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Ethiopia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Falkland Islands': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Faroe Islands': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Fiji': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Finland': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'France': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'French Guiana': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'French Polynesia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Gabon': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Gambia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Georgia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Germany': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Ghana': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Gibraltar': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Greece': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Greenland': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Grenada': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Guadeloupe': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Guam': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Guatemala': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Guernsey': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  '______': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Guinea': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Guinea-Bissau': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Guyana': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Haiti': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Honduras': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Hong Kong': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Hungary': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Iceland': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'India': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Indonesia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Iran': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Iraq': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Ireland': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Isle of Man': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Israel': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Italy': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Jamaica': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Japan': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Jersey': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Jordan': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Kazakhstan': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Kenya': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Kiribati': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Kosovo': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Kuwait': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Kyrgyzstan': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Laos': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Latvia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Lebanon': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Lesotho': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Liberia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Libya': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Liechtenstein': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Lithuania': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Luxembourg': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Macao': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Madagascar': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Malawi': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Malaysia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Maldives': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Mali': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Malta': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Marshall Islands': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Martinique': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Mauritania': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Mauritius': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Mayotte': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Mexico': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Micronesia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Moldova': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Monaco': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Mongolia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Montenegro': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Montserrat': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Morocco': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Mozambique': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Myanmar (Burma)': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Namibia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Nauru': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Nepal': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Netherlands': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'New Caledonia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'New Zealand': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Nicaragua': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Niger': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Nigeria': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Niue': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Norfolk Island': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'North Korea': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'North Macedonia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Northern Mariana Islands': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Norway': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Oman': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Pakistan': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Palau': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Palestine': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Panama': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Papua New Guinea': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Paraguay': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Peru': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Philippines': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Poland': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Portugal': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Puerto Rico': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Qatar': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Réunion': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Romania': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Russia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Rwanda': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Samoa': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'San Marino': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Saudi Arabia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'São Tomé & Príncipe': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Senegal': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Serbia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Seychelles': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Sierra Leone': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Singapore': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Sint Maarten': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Slovakia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Slovenia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Solomon Islands': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Somalia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'South Africa': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'South Korea': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'South Sudan': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Spain': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Sri Lanka': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Saint Barthélemy': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'St. Helena': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'St. Kitts & Nevis': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'St. Lucia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'St. Martin': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'St. Pierre & Miquelon': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'St. Vincent & Grenadines': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Sudan': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Suriname': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Svalbard & Jan Mayen': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Sweden': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Switzerland': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Syria': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Taiwan': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Tajikistan': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Tanzania': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Thailand': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Timor-Leste': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Togo': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Tokelau': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Tonga': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Trinidad & Tobago': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Tristan da Cunha': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Tunisia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Turkmenistan': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Turks & Caicos Islands': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Tuvalu': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Türkiye': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'U.S. Virgin Islands': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Uganda': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Ukraine': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'United Arab Emirates': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'United Kingdom': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'United States': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Uruguay': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Uzbekistan': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Vanuatu': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Vatican City': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Venezuela': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Vietnam': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Wallis & Futuna': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Western Sahara': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Yemen': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Zambia': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
  'Zimbabwe': {
    'description': '_______',
    'flag': '______',
    'phone': '______',
  },
};

const kCountriesWithCodes = {
  '\u{1F1E6}\u{1F1EB} Afghanistan (+93)': '+93',
  '\u{1F1E6}\u{1F1F1} Albania (+355)': '+355',
  '\u{1F1E9}\u{1F1FF} Algeria (+213)': '+213',
  '\u{1F1E6}\u{1F1F8} American Samoa (+1)': '+1',
  '\u{1F1E6}\u{1F1E9} Andorra (+376)': '+376',
  '\u{1F1E6}\u{1F1F4} Angola (+244)': '+244',
  '\u{1F1E6}\u{1F1EE} Anguilla (+1)': '+1',
  '\u{1F1E6}\u{1F1EC} Antigua & Barbuda (+1)': '+1',
  '\u{1F1E6}\u{1F1F7} Argentina (+54)': '+54',
  '\u{1F1E6}\u{1F1F2} Armenia (+374)': '+374',
  '\u{1F1E6}\u{1F1FC} Aruba (+297)': '+297',
  '\u{1F1F8}\u{1F1ED} Ascension Island (+247)': '+247',
  '\u{1F1E6}\u{1F1FA} Australia (+61)': '+61',
  '\u{1F1E6}\u{1F1F9} Austria (+43)': '+43',
  '\u{1F1E6}\u{1F1FF} Azerbaijan (+994)': '+994',
  '\u{1F1E6}\u{1F1FD} Åland Islands (+358)': '+358',
  '\u{1F1E7}\u{1F1F8} Bahamas (+1)': '+1',
  '\u{1F1E7}\u{1F1ED} Bahrain (+973)': '+973',
  '\u{1F1E7}\u{1F1E9} Bangladesh (+880)': '+880',
  '\u{1F1E7}\u{1F1E7} Barbados (+1)': '+1',
  '\u{1F1E7}\u{1F1FE} Belarus (+375)': '+375',
  '\u{1F1E7}\u{1F1EA} Belgium (+32)': '+32',
  '\u{1F1E7}\u{1F1FF} Belize (+501)': '+501',
  '\u{1F1E7}\u{1F1EF} Benin (+229)': '+229',
  '\u{1F1E7}\u{1F1F2} Bermuda (+1)': '+1',
  '\u{1F1E7}\u{1F1F9} Bhutan (+975)': '+975',
  '\u{1F1E7}\u{1F1F4} Bolivia (+591)': '+591',
  '\u{1F1E7}\u{1F1E6} Bosnia & Herzegovina (+387)': '+387',
  '\u{1F1E7}\u{1F1FC} Botswana (+267)': '+267',
  '\u{1F1E7}\u{1F1F7} Brazil (+55)': '+55',
  '\u{1F1FB}\u{1F1EC} British Virgin Islands (+1)': '+1',
  '\u{1F1E7}\u{1F1F3} Brunei (+673)': '+673',
  '\u{1F1E7}\u{1F1EC} Bulgaria (+359)': '+359',
  '\u{1F1E7}\u{1F1EB} Burkina Faso (+226)': '+226',
  '\u{1F1E7}\u{1F1EE} Burundi (+257)': '+257',
  '\u{1F1F0}\u{1F1ED} Cambodia (+855)': '+855',
  '\u{1F1E8}\u{1F1F2} Cameroon (+237)': '+237',
  '\u{1F1E8}\u{1F1E6} Canada (+1)': '+1',
  '\u{1F1E8}\u{1F1FB} Cape Verde (+238)': '+238',
  '\u{1F1E7}\u{1F1F6} Caribbean Netherlands (+599)': '+599',
  '\u{1F1F0}\u{1F1FE} Cayman Islands (+1)': '+1',
  '\u{1F1E8}\u{1F1EB} Central African Republic (+236)': '+236',
  '\u{1F1F9}\u{1F1E9} Chad (+235)': '+235',
  '\u{1F1EE}\u{1F1F4} Chagos Archipelago (+246)': '+246',
  '\u{1F1E8}\u{1F1F1} Chile (+56)': '+56',
  '\u{1F1E8}\u{1F1F3} China mainland (+86)': '+86',
  '\u{1F1E8}\u{1F1FD} Christmas Island (+61)': '+61',
  '\u{1F1E8}\u{1F1E8} Cocos (Keeling) Islands (+61)': '+61',
  '\u{1F1E8}\u{1F1F4} Columbia (+57)': '+57',
  '\u{1F1F0}\u{1F1F2} Comoros (+269)': '+269',
  '\u{1F1E8}\u{1F1EC} Congo - Brazzaville (+242)': '+242',
  '\u{1F1E8}\u{1F1EC} Congo - Kinshasa (+243)': '+243',
  '\u{1F1E8}\u{1F1F0} Cook Islands (+682)': '+682',
  '\u{1F1E8}\u{1F1F7} Costa Rica (+506)': '+506',
  '\u{1F1E8}\u{1F1EE} Côte d\'lvoire (+225)': '+225',
  '\u{1F1ED}\u{1F1F7} Croatia (+385)': '+385',
  '\u{1F1E8}\u{1F1FA} Cuba (+53)': '+53',
  '\u{1F1E8}\u{1F1FC} Curaçao (+599)': '+599',
  '\u{1F1E8}\u{1F1FE} Cyprus (+357)': '+357',
  '\u{1F1E8}\u{1F1FF} Czechia (+420)': '+420',
  '\u{1F1E9}\u{1F1F0} Denmark (+45)': '+45',
  '\u{1F1E9}\u{1F1EF} Djibouti (+253)': '+253',
  '\u{1F1E9}\u{1F1F2} Dominica (+1)': '+1',
  '\u{1F1E9}\u{1F1F4} Dominican Republic (+1)': '+1',
  '\u{1F1EA}\u{1F1E8} Ecuador (+593)': '+593',
  '\u{1F1EA}\u{1F1EC} Egypt (+20)': '+20',
  '\u{1F1F8}\u{1F1FB} El Salvador (+503)': '+503',
  '\u{1F1EC}\u{1F1F6} Equatorial Guinea (+240)': '+240',
  '\u{1F1EA}\u{1F1F7} Eritrea (+291)': '+291',
  '\u{1F1EA}\u{1F1EA} Estonia (+372)': '+372',
  '\u{1F1F8}\u{1F1FF} Eswatini (+268)': '+268',
  '\u{1F1EA}\u{1F1F9} Ethiopia (+251)': '+251',
  '\u{1F1EB}\u{1F1F0} Falkland Islands (+500)': '+500',
  '\u{1F1EB}\u{1F1F4} Faroe Islands (+298)': '+298',
  '\u{1F1EB}\u{1F1EF} Fiji (+679)': '+679',
  '\u{1F1EB}\u{1F1EE} Finland (+358)': '+358',
  '\u{1F1EB}\u{1F1F7} France (+33)': '+33',
  '\u{1F1EC}\u{1F1EB} French Guiana (+594)': '+594',
  '\u{1F1F5}\u{1F1EB} French Polynesia (+689)': '+689',
  '\u{1F1EC}\u{1F1E6} Gabon (+241)': '+241',
  '\u{1F1EC}\u{1F1F2} Gambia (+220)': '+220',
  '\u{1F1EC}\u{1F1EC} Georgia (+995)': '+995',
  '\u{1F1E9}\u{1F1EA} Germany (+49)': '+49',
  '\u{1F1EC}\u{1F1ED} Ghana (+233)': '+233',
  '\u{1F1EC}\u{1F1EE} Gibraltar (+350)': '+350',
  '\u{1F1EC}\u{1F1F7} Greece (+30)': '+30',
  '\u{1F1EC}\u{1F1F1} Greenland (+299)': '+299',
  '\u{1F1EC}\u{1F1E9} Grenada (+1)': '+1',
  '\u{1F1EC}\u{1F1F5} Guadeloupe (+590)': '+590',
  '\u{1F1EC}\u{1F1FA} Guam (+1)': '+1',
  '\u{1F1EC}\u{1F1F9} Guatemala (+502)': '+502',
  '\u{1F1EC}\u{1F1EC} Guernsey (+44)': '+44',
  '\u{1F1EC}\u{1F1F3} Guinea (+224)': '+224',
  '\u{1F1EC}\u{1F1FC} Guinea-Bissau (+245)': '+245',
  '\u{1F1EC}\u{1F1FE} Guyana (+592)': '+592',
  '\u{1F1ED}\u{1F1F9} Haiti (+509)': '+509',
  '\u{1F1ED}\u{1F1F3} Honduras (+504)': '+504',
  '\u{1F1ED}\u{1F1F0} Hong Kong (+852)': '+852',
  '\u{1F1ED}\u{1F1FA} Hungary (+36)': '+36',
  '\u{1F1EE}\u{1F1F8} Iceland (+354)': '+354',
  '\u{1F1EE}\u{1F1F3} India (+91)': '+91',
  '\u{1F1EE}\u{1F1E9} Indonesia (+62)': '+62',
  '\u{1F1EE}\u{1F1F7} Iran (+98)': '+98',
  '\u{1F1EE}\u{1F1F6} Iraq (+964)': '+964',
  '\u{1F1EE}\u{1F1EA} Ireland (+353)': '+353',
  '\u{1F1EE}\u{1F1F2} Isle of Man (+44)': '+44',
  '\u{1F1EE}\u{1F1F1} Israel (+972)': '+972',
  '\u{1F1EE}\u{1F1F9} Italy (+39)': '+39',
  '\u{1F1EF}\u{1F1F2} Jamaica (+1)': '+1',
  '\u{1F1EF}\u{1F1F5} Japan (+81)': '+81',
  '\u{1F1EF}\u{1F1EA} Jersey (+44)': '+44',
  '\u{1F1EF}\u{1F1F4} Jordan (+962)': '+962',
  '\u{1F1F0}\u{1F1FF} Kazakhstan (+7)': '+7',
  '\u{1F1F0}\u{1F1EA} Kenya (+254)': '+254',
  '\u{1F1F0}\u{1F1EE} Kiribati (+686)': '+686',
  '\u{1F1FD}\u{1F1F0} Kosovo (+383)': '+383',
  '\u{1F1F0}\u{1F1FC} Kuwait (+965)': '+965',
  '\u{1F1F0}\u{1F1EC} Kyrgyzstan (+996)': '+996',
  '\u{1F1F1}\u{1F1E6} Laos (+856)': '+856',
  '\u{1F1F1}\u{1F1FB} Latvia (+371)': '+371',
  '\u{1F1F1}\u{1F1E7} Lebanon (+961)': '+961',
  '\u{1F1F1}\u{1F1F8} Lesotho (+266)': '+266',
  '\u{1F1F1}\u{1F1F7} Liberia (+231)': '+231',
  '\u{1F1F1}\u{1F1FE} Libya (+218)': '+218',
  '\u{1F1F1}\u{1F1EE} Liechtenstein (+423)': '+423',
  '\u{1F1F1}\u{1F1F9} Lithuania (+370)': '+370',
  '\u{1F1F1}\u{1F1FA} Luxembourg (+352)': '+352',
  '\u{1F1F2}\u{1F1F4} Macao (+853)': '+853',
  '\u{1F1F2}\u{1F1EC} Madagascar (+261)': '+261',
  '\u{1F1F2}\u{1F1FC} Malawi (+265)': '+265',
  '\u{1F1F2}\u{1F1FE} Malaysia (+60)': '+60',
  '\u{1F1F2}\u{1F1FB} Maldives (+960)': '+960',
  '\u{1F1F2}\u{1F1F1} Mali (+223)': '+223',
  '\u{1F1F2}\u{1F1F9} Malta (+356)': '+356',
  '\u{1F1F2}\u{1F1ED} Marshall Islands (+692)': '+692',
  '\u{1F1F2}\u{1F1F6} Martinique (+596)': '+596',
  '\u{1F1F2}\u{1F1F7} Mauritania (+222)': '+222',
  '\u{1F1F2}\u{1F1FA} Mauritius (+230)': '+230',
  '\u{1F1FE}\u{1F1F9} Mayotte (+262)': '+262',
  '\u{1F1F2}\u{1F1FD} Mexico (+52)': '+52',
  '\u{1F1EB}\u{1F1F2} Micronesia (+691)': '+691',
  '\u{1F1F2}\u{1F1E9} Moldova (+373)': '+373',
  '\u{1F1F2}\u{1F1E8} Monaco (+377)': '+377',
  '\u{1F1F2}\u{1F1F3} Mongolia (+976)': '+976',
  '\u{1F1F2}\u{1F1EA} Montenegro (+382)': '+382',
  '\u{1F1F2}\u{1F1F8} Montserrat (+1)': '+1',
  '\u{1F1F2}\u{1F1E6} Morocco (+212)': '+212',
  '\u{1F1F2}\u{1F1FF} Mozambique (+258)': '+258',
  '\u{1F1F2}\u{1F1F2} Myanmar (Burma) (+95)': '+95',
  '\u{1F1F3}\u{1F1E6} Namibia (+264)': '+264',
  '\u{1F1F3}\u{1F1F7} Nauru (+674)': '+674',
  '\u{1F1F3}\u{1F1F5} Nepal (+977)': '+977',
  '\u{1F1F3}\u{1F1F1} Netherlands (+31)': '+31',
  '\u{1F1F3}\u{1F1E8} New Caledonia (+687)': '+687',
  '\u{1F1F3}\u{1F1FF} New Zealand (+64)': '+64',
  '\u{1F1F3}\u{1F1EE} Nicaragua (+505)': '+505',
  '\u{1F1F3}\u{1F1EA} Niger (+227)': '+227',
  '\u{1F1F3}\u{1F1EC} Nigeria (+234)': '+234',
  '\u{1F1F3}\u{1F1FA} Niue (+683)': '+683',
  '\u{1F1F3}\u{1F1EB} Norfolk Island (+672)': '+672',
  '\u{1F1F0}\u{1F1F5} North Korea (+850)': '+850',
  '\u{1F1F2}\u{1F1F0} North Macedonia (+389)': '+389',
  '\u{1F1F2}\u{1F1F5} Northern Mariana Islands (+1)': '+1',
  '\u{1F1F3}\u{1F1F4} Norway (+47)': '+47',
  '\u{1F1F4}\u{1F1F2} Oman (+968)': '+968',
  '\u{1F1F5}\u{1F1F0} Pakistan (+92)': '+92',
  '\u{1F1F5}\u{1F1FC} Palau (+680)': '+680',
  '\u{1F1F5}\u{1F1F8} Palestine (+970)': '+970',
  '\u{1F1F5}\u{1F1E6} Panama (+507)': '+507',
  '\u{1F1F5}\u{1F1EC} Papua New Guinea (+675)': '+675',
  '\u{1F1F5}\u{1F1FE} Paraguay (+595)': '+595',
  '\u{1F1F5}\u{1F1EA} Peru (+51)': '+51',
  '\u{1F1F5}\u{1F1ED} Philippines (+63)': '+63',
  '\u{1F1F5}\u{1F1F1} Poland (+48)': '+48',
  '\u{1F1F5}\u{1F1F9} Portugal (+351)': '+351',
  '\u{1F1F5}\u{1F1F7} Puerto Rico (+1)': '+1',
  '\u{1F1F6}\u{1F1E6} Qatar (+974)': '+974',
  '\u{1F1F7}\u{1F1EA} Réunion (+262)': '+262',
  '\u{1F1F7}\u{1F1F4} Romania (+40)': '+40',
  '\u{1F1F7}\u{1F1FA} Russia (+7)': '+7',
  '\u{1F1F7}\u{1F1FC} Rwanda (+250)': '+250',
  '\u{1F1FC}\u{1F1F8} Samoa (+685)': '+685',
  '\u{1F1F8}\u{1F1F2} San Marino (+378)': '+378',
  '\u{1F1F8}\u{1F1E6} Saudi Arabia (+966)': '+966',
  '\u{1F1F8}\u{1F1F9} São Tomé & Príncipe (+239)': '+239',
  '\u{1F1F8}\u{1F1F3} Senegal (+221)': '+221',
  '\u{1F1F7}\u{1F1F8} Serbia (+381)': '+381',
  '\u{1F1F8}\u{1F1E8} Seychelles (+248)': '+248',
  '\u{1F1F8}\u{1F1F1} Sierra Leone (+232)': '+232',
  '\u{1F1F8}\u{1F1EC} Singapore (+65)': '+65',
  '\u{1F1F8}\u{1F1FD} Sint Maarten (+1)': '+1',
  '\u{1F1F8}\u{1F1F0} Slovakia (+421)': '+421',
  '\u{1F1F8}\u{1F1EE} Slovenia (+386)': '+386',
  '\u{1F1F8}\u{1F1E7} Solomon Islands (+677)': '+677',
  '\u{1F1F8}\u{1F1F4} Somalia (+252)': '+252',
  '\u{1F1FF}\u{1F1E6} South Africa (+27)': '+27',
  '\u{1F1F0}\u{1F1F7} South Korea (+82)': '+82',
  '\u{1F1F8}\u{1F1F8} South Sudan (+211)': '+211',
  '\u{1F1EA}\u{1F1F8} Spain (+34)': '+34',
  '\u{1F1F1}\u{1F1F0} Sri Lanka (+94)': '+94',
  '\u{1F1E7}\u{1F1F1} Saint Barthélemy (+590)': '+590',
  '\u{1F1F8}\u{1F1ED} St. Helena (+290)': '+290',
  '\u{1F1F0}\u{1F1F3} St. Kitts & Nevis (+1)': '+1',
  '\u{1F1F1}\u{1F1E8} St. Lucia (+1)': '+1',
  '\u{1F1F2}\u{1F1EB} St. Martin (+590)': '+590',
  '\u{1F1F5}\u{1F1F2} St. Pierre & Miquelon (+508)': '+508',
  '\u{1F1FB}\u{1F1E8} St. Vincent & Grenadines (+1)': '+1',
  '\u{1F1F8}\u{1F1E9} Sudan (+249)': '+249',
  '\u{1F1F8}\u{1F1F7} Suriname (+597)': '+597',
  '\u{1F1F8}\u{1F1EF} Svalbard & Jan Mayen (+47)': '+47',
  '\u{1F1F8}\u{1F1EA} Sweden (+46)': '+46',
  '\u{1F1E8}\u{1F1ED} Switzerland (+41)': '+41',
  '\u{1F1F8}\u{1F1FE} Syria (+963)': '+963',
  '\u{1F1F9}\u{1F1FC} Taiwan (+886)': '+886',
  '\u{1F1F9}\u{1F1EF} Tajikistan (+992)': '+992',
  '\u{1F1F9}\u{1F1FF} Tanzania (+255)': '+255',
  '\u{1F1F9}\u{1F1ED} Thailand (+66)': '+66',
  '\u{1F1F9}\u{1F1F1} Timor-Leste (+670)': '+670',
  '\u{1F1F9}\u{1F1EC} Togo (+228)': '+228',
  '\u{1F1F9}\u{1F1F0} Tokelau (+690)': '+690',
  '\u{1F1F9}\u{1F1EC} Tonga (+676)': '+676',
  '\u{1F1F9}\u{1F1F9} Trinidad & Tobago (+1)': '+1',
  '\u{1F1F8}\u{1F1ED} Tristan da Cunha (+290)': '+290',
  '\u{1F1F9}\u{1F1F3} Tunisia (+216)': '+216',
  '\u{1F1F9}\u{1F1F2} Turkmenistan (+993)': '+993',
  '\u{1F1F9}\u{1F1E8} Turks & Caicos Islands (+1)': '+1',
  '\u{1F1F9}\u{1F1FB} Tuvalu (+688)': '+688',
  '\u{1F1F9}\u{1F1F7} Türkiye (+90)': '+90',
  '\u{1F1FB}\u{1F1EE} U.S. Virgin Islands (+1)': '+1',
  '\u{1F1FA}\u{1F1EC} Uganda (+256)': '+256',
  '\u{1F1FA}\u{1F1E6} Ukraine (+380)': '+380',
  '\u{1F1E6}\u{1F1EA} United Arab Emirates (+971)': '+971',
  '\u{1F1EC}\u{1F1E7} United Kingdom (+44)': '+44',
  '\u{1F1FA}\u{1F1F8} United States (+1)': '+1',
  '\u{1F1FA}\u{1F1FE} Uruguay (+598)': '+598',
  '\u{1F1FA}\u{1F1FF} Uzbekistan (+998)': '+998',
  '\u{1F1FB}\u{1F1FA} Vanuatu (+678)': '+678',
  '\u{1F1FB}\u{1F1E6} Vatican City (+39)': '+39',
  '\u{1F1FB}\u{1F1EA} Venezuela (+58)': '+58',
  '\u{1F1FB}\u{1F1F3} Vietnam (+84)': '+84',
  '\u{1F1FC}\u{1F1EB} Wallis & Futuna (+681)': '+681',
  '\u{1F1EA}\u{1F1ED} Western Sahara (+212)': '+212',
  '\u{1F1FE}\u{1F1EA} Yemen (+967)': '+967',
  '\u{1F1FF}\u{1F1F2} Zambia (+260)': '+260',
  '\u{1F1FF}\u{1F1FC} Zimbabwe (+263)': '+263',
};
